# Generated by Django 5.2.8 on 2025-12-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WriterQuotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("quote1", models.TextField()),
                ("quote2", models.TextField()),
                ("quote3", models.TextField()),
                ("quote4", models.TextField()),
                ("quote5", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Quote",
        ),
        migrations.DeleteModel(
            name="Writer",
        ),
    ]
